"""Plumbing shared by the three question scripts.

Keeps the report reproducible: figures are written as vector PDFs into ``figs/`` and
every number quoted in the write-up is exported to ``results/`` as a LaTeX macro, so
nothing has to be transcribed by hand.
"""

from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parent.parent
FIGS = ROOT / "figs"
RESULTS = ROOT / "results"

# Match the report: serif text, and fonts embedded as Type 42 so the PDF is portable.
mpl.rcParams.update({
    "figure.dpi": 120,
    "savefig.bbox": "tight",
    "font.family": "serif",
    "axes.grid": True,
    "grid.alpha": 0.3,
    "pdf.fonttype": 42,
})


def savefig(fig, name: str) -> Path:
    """Write ``fig`` to figs/<name>.pdf (vector, so it stays sharp at any zoom)."""
    FIGS.mkdir(exist_ok=True)
    path = FIGS / f"{name}.pdf"
    fig.savefig(path)
    print(f"wrote {path.relative_to(ROOT)}")
    return path


def write_results(question: str, values: dict) -> Path:
    """Export ``values`` to results/<question>.tex as \\setresult macros.

    Keys may contain dots and digits, e.g. ``{"q1.logml.M1": -14.2891}``; the report
    then cites the number as ``\\result{q1.logml.M1}``. Floats are formatted to 4
    significant-ish decimals by default -- pass a preformatted string for full control.
    """
    RESULTS.mkdir(exist_ok=True)
    path = RESULTS / f"{question}.tex"
    lines = ["% Generated by code/ -- do not edit by hand.\n"]
    for key, value in values.items():
        formatted = f"{value:.4f}" if isinstance(value, float) else str(value)
        lines.append(f"\\setresult{{{key}}}{{{formatted}}}\n")
    path.write_text("".join(lines))
    print(f"wrote {path.relative_to(ROOT)} ({len(values)} values)")
    return path


def show():
    """No-op hook so scripts can be run headless or interactively."""
    plt.show()
